services:
  db:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      provider-network:
        aliases:
          - db
        ipv4_address: 170.5.100.5

  provider:
    image: redbird9623/forecast:0.0.2
    depends_on:
      - db
    entrypoint:
    command:
      - --WORKERS_NUM=5
      - --NODE=https://allora-rpc.v2.testnet.allora.network:443
      - --CONNECTION=postgres://app:app@170.5.100.5:5432/app
      - --AWS_ACCESS_KEY=
      - --AWS_SECURITY_KEY=
      - --S3_BUCKET_NAME=allora-testnet-1-indexer-backups
      - --S3_FILE_KEY=pgdump-20240723-20-47-11.dump.gz
    networks:
      provider-network:
        aliases:
          - db
        ipv4_address: 170.5.100.10

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8081:8080

volumes:
  data:

networks:
  provider-network:
    driver: bridge
    ipam:
      config:
        - subnet: 170.5.100.0/24
